### ISSUE TITLE
WrapVTK incompatible with VTK9.0.1

### ISSUE THREAD

**Issue by ghost** [dgobbi/WrapVTK#2]
When I compiled with Cmake, it give me this message
```
CMake Deprecation Warning at C:/local/VTK-9.0.1/lib/cmake/vtk-9.0/vtk-use-file-deprecated.cmake:1 (message):
  The `VTK_USE_FILE` is no longer used starting with 8.90.
Call Stack (most recent call first):
```

**Comment by dgobbi** [comment]
Wow, I didn't know that anyone was using this.  I haven't updated the repository for a year.

Thanks for your report.  Unfortunately, I cannot give a timeline for when VTK 9 will be supported by WrapVTK, because the cmake files for VTK 9 are completely different from earlier versions of VTK.

**Comment by abrahamperz** [comment]
In version 9.0.1 VTK_USE_FILE does not exist anymore. For version upper than 8.90, replace in CMake file VTK_INCLUDE_DIRS instead of VTK_USE_FILE as the following example

```
FIND_PACKAGE(VTK)
IF (VTK_FOUND)
  IF (VTK_INCLUDE_DIRS)
    # INCLUDE (${VTK_USE_FILE})
	include_directories(${VTK_INCLUDE_DIRS})
  ELSE (VTK_INCLUDE_DIRS)
    MESSAGE(WARNING "No VTK_USE_FILE, perhaps VTK is too recent?")
  ENDIF (VTK_INCLUDE_DIRS)
ENDIF (VTK_FOUND)
```

**Comment by dgobbi** [comment]
WrapVTK has now been updated to produce XML files for VTK 9.
